kits:
    starter: default
    default:
        items:
        - 278 1 dig_speed:2 name:&eDemanta_Haki
        - 279 1 dig_speed:2 name:&eDemanta_Exi
        - 277 1 dig_speed:3 name:&eDemanta_Skofla
        - 284 1 durability:3 name:&eVerndunar_Skoflan
        #Til að gera bok þá er það - book <nafn á texta skjalinu með bókini>
        - book book
msg:
    kitsuccsess: '&eÞér hefur verið fært kittið: {kit}'
    kiterror: '&cÞetta kit er ekki til!'