name: SandkassinnKits
author: [TheNokar]
version: 0.3
loadbefore: [CommandBook, WorldEdit, WorldGuard]
main: net.Plommer.SandkassinnKits.SandkassinnKits
commands:
    kit:
        description: The default kits command!
        aliases: [kits]
permissions:
    sandkassinnkits.*:
        default: op
        description: Give players with op everything by default